# Site settings
title: Yoonsuk Paik | portfolio
description: Yoonsuk Paik | portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yoonsuk Paik
user_description: Full stack engineer with nearly 2 years of professional experiences in programming. <br/>Expert and highly familiar with a wide variety of programming languages and database. <br/>Possess Bachelor of Science Degree in Bachelor of Science in Logistics and Supply Chain Management.
user_title: Full Stack Developer
email: macxpaik@gmail.com
twitter_username:
github_username:  macpaik
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
