# Site settings
title: Yoonsuk Paik | portfolio
description: Yoonsuk Paik | portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yoonsuk Paik
user_description: Experienced full stack developer with 1+ years in web development and software engineering in general.<br/>Thank you for visiting my portfolio, hope you enjoy!
user_title: Full Stack Developer
email: macxpaik@gmail.com
twitter_username:
github_username:  macpaik
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
